# Generated by Django 5.0.4 on 2024-04-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingproduct',
            old_name='quantity',
            new_name='quantity_replenished',
        ),
        migrations.AddField(
            model_name='pendingproduct',
            name='pending_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
