# Generated by Django 5.0.4 on 2024-04-16 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_quantity_pendingproduct_quantity_replenished_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='quantity',
        ),
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('moviment', models.CharField(choices=[('entrada', 'entrada'), ('saída', 'saída')], max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_history', to='product.productitem')),
            ],
        ),
        migrations.DeleteModel(
            name='PendingProduct',
        ),
    ]
