# Generated by Django 5.0.4 on 2024-04-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_hospital_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='city',
            field=models.CharField(blank=True, max_length=255, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='state',
            field=models.CharField(blank=True, max_length=2, verbose_name='estado'),
        ),
    ]
